// Reputable email providers with their characteristics
export const reputableDomains = {
  // Google
  "gmail.com": {
    provider: "Google",
    type: "personal",
    reputation: 0.95,
    features: {
      plusAddressing: true,
      dotAddressing: true,
    },
    securityExpectations: {
      spf: true,
      dkim: true,
      dmarc: true,
    },
    subdomains: {
      www: true,
      mail: true,
    },
  },
  "googlemail.com": {
    provider: "Google",
    type: "personal",
    reputation: 0.95,
    features: {
      plusAddressing: true,
      dotAddressing: true,
    },
    securityExpectations: {
      spf: true,
      dkim: true,
      dmarc: true,
    },
    subdomains: {
      www: true,
      mail: true,
    },
  },

  // Microsoft
  "outlook.com": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: {
      plusAddressing: true,
      dotAddressing: false,
    },
    securityExpectations: {
      spf: true,
      dkim: true,
      dmarc: true,
    },
    subdomains: {
      www: true,
      mail: true,
    },
  },
  "hotmail.com": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: {
      plusAddressing: true,
      dotAddressing: false,
    },
    securityExpectations: {
      spf: true,
      dkim: true,
      dmarc: true,
    },
    subdomains: {
      www: true,
      mail: true,
    },
  },
  "live.com": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: {
      plusAddressing: true,
      dotAddressing: false,
    },
    securityExpectations: {
      spf: true,
      dkim: true,
      dmarc: true,
    },
    subdomains: {
      www: true,
      mail: true,
    },
  },
  "msn.com": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: {
      plusAddressing: true,
      dotAddressing: false,
    },
    securityExpectations: {
      spf: true,
      dkim: true,
      dmarc: true,
    },
    subdomains: {
      www: true,
      mail: true,
    },
  },

  // Additional Microsoft domains
  "hotmail.co.uk": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.fr": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.it": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.de": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.es": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.be": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.ca": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.com.ar": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "hotmail.com.br": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "live.co.uk": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "live.fr": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "live.it": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "live.nl": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "live.com.au": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "windowslive.com": {
    provider: "Microsoft",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Yahoo (International)
  "yahoo.com": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.co.uk": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.fr": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.it": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.de": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.es": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.co.jp": {
    provider: "Yahoo Japan",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.com.br": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.co.in": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.com.au": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.com.ar": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.com.mx": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.ca": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.com.sg": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.nl": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.co.nz": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.com.hk": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yahoo.com.tw": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "ymail.com": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "rocketmail.com": {
    provider: "Yahoo",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Apple
  "icloud.com": {
    provider: "Apple",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "me.com": {
    provider: "Apple",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "mac.com": {
    provider: "Apple",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // AOL
  "aol.com": {
    provider: "AOL",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "aim.com": {
    provider: "AOL",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // US ISPs
  "comcast.net": {
    provider: "Comcast",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "verizon.net": {
    provider: "Verizon",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "att.net": {
    provider: "AT&T",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "cox.net": {
    provider: "Cox",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "charter.net": {
    provider: "Charter",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "earthlink.net": {
    provider: "EarthLink",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "juno.com": {
    provider: "Juno",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // European ISPs and Providers
  "web.de": {
    provider: "Web.de",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "gmx.de": {
    provider: "GMX",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "gmx.net": {
    provider: "GMX",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "t-online.de": {
    provider: "Deutsche Telekom",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "orange.fr": {
    provider: "Orange",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "free.fr": {
    provider: "Free",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "laposte.net": {
    provider: "La Poste",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "sfr.fr": {
    provider: "SFR",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "neuf.fr": {
    provider: "SFR Neuf",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "alice.it": {
    provider: "Alice",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "virgilio.it": {
    provider: "Virgilio",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "libero.it": {
    provider: "Libero",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "bluewin.ch": {
    provider: "Bluewin",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Australian/NZ ISPs
  "bigpond.com": {
    provider: "Telstra Bigpond",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "bigpond.net.au": {
    provider: "Telstra Bigpond",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "optusnet.com.au": {
    provider: "Optus",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Canadian ISPs
  "shaw.ca": {
    provider: "Shaw",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "sympatico.ca": {
    provider: "Bell Sympatico",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Brazilian Providers
  "uol.com.br": {
    provider: "UOL",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "bol.com.br": {
    provider: "BOL",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "terra.com.br": {
    provider: "Terra",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "ig.com.br": {
    provider: "IG",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Asian Providers
  "qq.com": {
    provider: "Tencent QQ",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "163.com": {
    provider: "NetEase",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "126.com": {
    provider: "NetEase",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Russian Providers
  "mail.ru": {
    provider: "Mail.ru",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "yandex.ru": {
    provider: "Yandex",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "rambler.ru": {
    provider: "Rambler",
    type: "personal",
    reputation: 0.85,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },

  // Secure Email Providers
  "proton.me": {
    provider: "Proton",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "protonmail.com": {
    provider: "Proton",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "tutanota.com": {
    provider: "Tutanota",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: false, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "fastmail.com": {
    provider: "Fastmail",
    type: "personal",
    reputation: 0.9,
    features: { plusAddressing: true, dotAddressing: false },
    securityExpectations: { spf: true, dkim: true, dmarc: true },
    subdomains: { www: true, mail: true },
  },
  "microsoft.com": {
    provider: "Microsoft",
    type: "corporate",
    reputation: 0.95,
    features: {
      plusAddressing: true,
      dotAddressing: false,
    },
    securityExpectations: {
      spf: true,
      dkim: true,
      dmarc: true,
    },
    subdomains: {
      www: true,
      mail: true,
    },
  },
};
